[package]
name = "divvunspell"
version = "0.2.1"
edition = "2018"

# Has the same name as the real divvunspell. This is just the Python wrapper.
publish = false 

[lib]
name = "divvunspell"
crate-type = ["cdylib"]

[dependencies]
divvunspell = { version = "1.0.0-beta.3" } # { git = "https://github.com/divvun/divvunspell", branch = "main", features = ["compression"] }
pyo3 = { version="0.13.2" , features = ["extension-module"]}
