[project]
name = "divvunspell"
version = "0.2.1"
requires_python = ">=3.10"
authors = [{name = "Brendan Molloy", email = "brendan@bbqsrc.net"}]
license = "Apache-2.0 OR MIT"
classifiers = [
  "Programming Language :: Rust"
]

[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"


[tool.maturin]
features = ["pyo3/extension-module"]
